"""Synthesis engine: generates a structured thesis paper from top-10 sources.

Strategy:
  1. Try a local Ollama model (OpenAI-compatible endpoint).
  2. If Ollama is unreachable, fall back to a template-based assembler
     that still produces a coherent, properly formatted paper purely from
     the search snippets — no LLM needed.
"""
from __future__ import annotations

import asyncio
import json
from collections.abc import AsyncIterator

import requests
from loguru import logger

from models import SearchResult

OLLAMA_URL   = "http://localhost:11434/v1/chat/completions"
OLLAMA_MODEL = "qwen2.5:14b-instruct"
TIMEOUT_S    = 90

SYSTEM_PROMPT = """\
You are ThesisAI, an expert academic writing assistant.
Given a research question and a numbered list of sources, write a complete, \
well-structured academic thesis paper with the following sections:
  1. Abstract
  2. Introduction
  3. Literature Review (cite each source as [1], [2], … where relevant)
  4. Discussion
  5. Conclusion
  6. References

Use formal, academic English. Every factual claim must be backed by a \
bracketed citation. Do NOT invent facts not present in the sources.\
"""


# ── Ollama streaming helper (runs in a thread) ────────────────────────────────

def _stream_sync(query: str, sources_text: str):
    payload = {
        "model":       OLLAMA_MODEL,
        "temperature": 0.3,
        "stream":      True,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": f"Research question: {query}\n\nSources:\n{sources_text}"},
        ],
    }
    with requests.post(OLLAMA_URL, json=payload, timeout=TIMEOUT_S, stream=True) as resp:
        resp.raise_for_status()
        for line in resp.iter_lines(decode_unicode=True):
            if not line or not line.startswith("data:"):
                continue
            data = line[len("data:"):].strip()
            if data == "[DONE]":
                break
            try:
                chunk = json.loads(data)
                delta = chunk["choices"][0]["delta"].get("content")
                if delta:
                    yield delta
            except (json.JSONDecodeError, KeyError, IndexError):
                continue


# ── Fallback template (no LLM) ────────────────────────────────────────────────

def _template_paper(query: str, results: list[SearchResult]) -> str:
    refs = "\n".join(
        f"{r.index}. **{r.title}** — [Link]({r.url})" for r in results
    )
    snippets = "\n\n".join(
        f"**[{r.index}]** {r.title}\n> {r.snippet}" for r in results if r.snippet
    )
    paper = f"""# Research Synthesis: {query}

## Abstract
This paper synthesises findings from {len(results)} online sources regarding: *"{query}"*. The sources were retrieved automatically and cover peer-reviewed articles, preprints, and academic web pages.

## Introduction
The topic of *"{query}"* has attracted significant scholarly attention. This synthesis aims to present a coherent overview of the current state of knowledge, drawing on the top-ranked online sources available at the time of this search.

## Literature Review
Below is a review of the retrieved literature:

{snippets if snippets else 'No snippets available from search results.'}

## Discussion
The sources retrieved indicate that *"{query}"* is an active area of research. Researchers have explored various dimensions of this topic, as evidenced by the diversity of the sources listed in the References section below. Readers are encouraged to follow the URLs in the References for full-text access.

## Conclusion
This automated synthesis has identified {len(results)} relevant sources for the query *"{query}"*. A comprehensive literature review would require manual examination of each source's full text.

## References
{refs}

---
*Generated by Thesis AI (template mode — Ollama not available)*
"""
    return paper


# ── Public async streaming synthesizer ───────────────────────────────────────

def _format_sources(results: list[SearchResult]) -> str:
    lines = []
    for r in results:
        lines.append(f"[{r.index}] {r.title}\nURL: {r.url}\nSnippet: {r.snippet}")
    return "\n\n".join(lines) if lines else "(no sources)"


async def synthesize(query: str, results: list[SearchResult]) -> AsyncIterator[str]:
    """Yield paper tokens. Falls back to template if Ollama is offline."""
    sources_text = _format_sources(results)

    queue: asyncio.Queue[str | None] = asyncio.Queue()
    loop = asyncio.get_running_loop()
    ollama_available = True

    def producer():
        nonlocal ollama_available
        try:
            for token in _stream_sync(query, sources_text):
                loop.call_soon_threadsafe(queue.put_nowait, token)
        except Exception as exc:
            logger.warning(f"Ollama unavailable ({exc}); using template fallback")
            ollama_available = False
            fallback = _template_paper(query, results)
            # stream the fallback in small chunks
            chunk_size = 80
            for i in range(0, len(fallback), chunk_size):
                loop.call_soon_threadsafe(queue.put_nowait, fallback[i:i + chunk_size])
        finally:
            loop.call_soon_threadsafe(queue.put_nowait, None)

    loop.run_in_executor(None, producer)

    while True:
        token = await queue.get()
        if token is None:
            break
        yield token
